/// Flutter icons OwnerDashboard
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OwnerDashboard
///      fonts:
///       - asset: fonts/OwnerDashboard.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OwnerDashboard {
  OwnerDashboard._();

  static const _kFontFam = 'OwnerDashboard';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tenant = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listing = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
